language: java
jdk:
#  - oraclejdk7
#  - openjdk7
  - openjdk6
notifications:
  email:
    recipients:
      - luliang1984@gmail.com
    #on_success: [always|never|change]  default: change
    #on_failure: [always|never|change]  default: always
